name: CMake on multiple platforms

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  ubuntu_build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt install rpm

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Create packages
      working-directory: ${{github.workspace}}/build
      run: |
        cpack -G DEB
        cpack -G RPM

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ubuntu-pack
        path: |
          build/*.deb
          build/*.rpm

  windows_build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Create packages
      working-directory: ${{github.workspace}}/build
      run: |
        cpack -G WIX

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: win-pack
        path: build/*.msi

  macos_build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Create packages
      working-directory: ${{github.workspace}}/build
      run: |
        cpack -G DragNDrop

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-pack
        path: build/*.dmg
    
  create_release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4

    - name: download_ubuntu
      with:
          name: ubuntu-pack
          path: artifacts/linux

    - name:
      with:
          name: win-pack
          path: artifacts/windows
    - name: 
      with:
          name: macos-pack
          path: artifacts/macos
          
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.${{ github.run_number }}
        name: Release v1.${{ github.run_number }}
        files: |
          artifacts/linux/*
          artifacts/windows/*
          artifacts/macos/*